### ISSUE TITLE
[User][Model] Missing upcoming_events and previous_events method

### ISSUE THREAD

**Issue by heyapricot** [YellowPipe/Private-Events#8]
From point 5 of the Event Attendance section:
> 5. Modify the User’s Show page to separate those events which have occurred in the past (“Previously attended events”) from those which are occuring in the future (“Upcoming events”). You could do this by putting logic in your view. Don’t. Have your controller call separate model methods to retrieve each, e.g. @upcoming_events = current_user.upcoming_events and @prev_events = current_user.previous_events. You’ll get some practice with working with dates as well as building some queries.

**Comment by YellowPipe** [comment]
Later odin asks to refactor these methods 
> 7. Refactor the “upcoming” and “past” methods into simple scopes (remember scopes??).

**Comment by heyapricot** [comment]
I agree. Yet, instead of removing the methods from the `User` model you could have kept them and use the `Event` scope inside the `User` methods
